import MainLayout from "@/components/MainLayout";
import "./globals.css";
import MenuIconProvider from "@/context/MenuIcon";

export const metadata = {
  title: "Create Next App(Random-js)",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MenuIconProvider>
          <MainLayout>{children}</MainLayout>
        </MenuIconProvider>
      </body>
    </html>
  );
}
